### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by ConnectBhawna** [oras-project/oras-www#110] opened 2023-02-13 10:40 UTC
- When hovering over text, the color changes to dark blue, making it difficult to see in dark mode.
- We can change it into light colour.
![Screenshot from 2023-02-13 16-05-16](https://user-images.githubusercontent.com/81790585/218435848-505ac31d-df27-481c-9047-2561008f10b5.png)

what do you think @TerryHowe @FeynmanZhou

**Comment by TerryHowe** [comment] 2023-02-13 15:03
Yeh, I'm using dark mode and it seems like the blue is too dark in general, but mouse over for me turns it a lighter blue. Seems like some slight color adjustment would be good either way.

**Comment by ConnectBhawna** [comment] 2023-02-15 11:33
Yups @TerryHowe sir,
Can i work on creating the Pr for the same.

**Comment by yash7raut** [comment] 2023-05-18 11:12
This issue seems to be no longer relevant as I am unable to reproduce the reported problem. I recommend closing this issue. Thank you!

**Comment by TerryHowe** [comment] 2023-05-18 11:14
Yes, I think you are right

**Closed by TerryHowe** 2023-05-18 11:14 UTC
